// eslint-disable-next-line no-undef
module.exports = {
	rules: {
		// eslint-disable-next-line no-undef
		'use-numeric-separators': require('./lib/rules/use-numeric-separators'),
	},
	configs: {
		recommended: {
			plugins: ['salmon'],
			env: {
				browser: true,
				es2021: true,
				es6: true,
			},
			parserOptions: {
				ecmaVersion: 15,
				sourceType: 'module',
			},
			rules: {
				'salmon/use-numeric-separators': 'error',
			},
		},
		recommendedWithExternal: {
			plugins: ['salmon', 'import', 'eslint:recommended', 'prettier'],
			env: {
				browser: true,
				es2021: true,
				es6: true,
			},
			parserOptions: {
				ecmaVersion: 6,
				sourceType: 'module',
			},
			rules: {
				'array-callback-return': 'warn',
				'arrow-body-style': 'warn',
				curly: ['error', 'multi-line'],
				'consistent-return': 'error',
				'dot-notation': 'warn',
				eqeqeq: 'error',
				'no-alert': 'error',
				'no-array-constructor': 'warn',
				'no-caller': 'error',
				'no-duplicate-imports': 'error',
				'no-else-return': 'error',
				'no-empty-function': 'error',
				'no-eval': 'error',
				'no-extra-bind': 'error',
				'no-floating-decimal': 'error',
				'no-implied-eval': 'error',
				'no-lone-blocks': 'error',
				'no-lonely-if': 'warn',
				'no-magic-numbers': 'error',
				'no-multi-spaces': 'error',
				'no-new-func': 'error',
				'no-new-object': 'warn',
				'no-new-wrappers': 'error',
				'no-octal-escape': 'error',
				'no-param-reassign': 'error',
				'no-redeclare': 'error',
				'no-return-await': 'error',
				'no-self-compare': 'error',
				'no-throw-literal': 'error',
				'no-undef-init': 'warn',
				'no-unmodified-loop-condition': 'error',
				'no-unneeded-ternary': 'warn',
				'no-unused-expressions': 'error',
				'no-unused-labels': 'error',
				'no-unused-vars': 'warn',
				'no-useless-call': 'error',
				'no-useless-computed-key': 'warn',
				'no-useless-concat': 'warn',
				'no-useless-constructor': 'warn',
				'no-useless-rename': 'warn',
				'no-useless-return': 'warn',
				'no-useless-escape': 'error',
				'no-var': 'warn',
				'no-with': 'error',
				'object-shorthand': 'warn',
				'operator-assignment': 'warn',
				'prefer-arrow-callback': 'warn',
				'prefer-const': ['warn', { destructuring: 'all' }],
				'prefer-destructuring': ['error', { object: true, array: false }],
				'prefer-promise-reject-errors': 'error',
				'prefer-regex-literals': 'error',
				strict: 'warn',
				yoda: 'warn',

				'import/export': 'error',
				'import/extensions': 'warn',
				'import/newline-after-import': 'warn',
				'import/no-mutable-exports': 'warn',
				'import/order': 'warn',

				// custom
				'salmon/use-numeric-separators': 'error',
			},
		},
	},
};
